title: Michael C. Adams # your name (or website title) here
logo: "/images/profile22.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Regis University Graduate - May 2022
  <br><br>
  Master's of Science - Data Science 
  <br><br>
  <a href="https://www.linkedin.com/in/michael-adams-3b7938158/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
